### ISSUE TITLE
Gold data refresh

### ISSUE THREAD

**Issue by antiseptique** [Eldrni/the-elder-bar#11]
I have noticed that the bar does not refresh correctly for the gold, result is, the bar display incorrect informations.
![barinforefresh](https://user-images.githubusercontent.com/7832217/44953475-15457100-ae96-11e8-821c-30dd00daf802.PNG)

Going into a building witout loading time : no refresh
Going to another shrine in the same zone with small loading time : no refresh
Travel to another zone with normal loading time : no refresh
Reloadui : no refresh
Toggle on/off gold gadget then reloadui : no refresh
Logout/Login : no refresh
Restart the game : no refresh
Disabling all addons exept TEB : no refresh
From unknow events : sometime the bar refresh to the correct amount of gold

Triggering a gold event (buying/selling items at vendor) : Refresh but with the memorised info, not the real one, maybe the bar should scan again the gold instead of add/remove to the current stored info. (Probably the same with other gold events like chest, loot, quest etc)

**Comment by Eldrni** [comment]
This uses the built in ESO API gunction to get gold on your character and gold in the bank. That is run every time the bar updates, which is multiple times a second.

**Comment by Eldrni** [comment]
Btw that value is gold on your character + gold in the bank.

**Comment by antiseptique** [comment]
Indeed, for the moment I've altered the bar to only use "gold = goldc" (And it actually display what I need), imo it will be better to split it into a few toggles, character and character+bank, and maybe bank only too.

**Comment by Eldrni** [comment]
I’ll add an option in the next release

**Comment by Eldrni** [comment]
Fixed in Release 4.
