### ISSUE TITLE
Gadgets aren't always positioned correctly vertically

### ISSUE THREAD

**Issue by Eldrni** [Eldrni/the-elder-bar#7]
drcolombo wrote that gadgets aren't positioned correctly. 
[Screenshot](https://imgur.com/a/ZX43huV)

**Comment by drcolombo** [comment]
An interesting thing: if I change the font "ZoFontChat" to "ZoFontGameSmall", then the controls are going down... [https://imgur.com/a/fE3EUe6](url)

**Comment by Eldrni** [comment]
It’s probably due to how I chain all the gadgets together. Each one is positioned relative to the previous. One pixel difference can throw them all off and i think that’s what you’re seeing. I’ve got an idea of how to fix this when I get back off vacation.

**Comment by Eldrni** [comment]
Fixed in Release 4.

**Comment by drcolombo** [comment]
Thanks. It's really fixed - now the bar is perfectly aligned :)
