### ISSUE TITLE
Soul gems aren't being counted correctly

### ISSUE THREAD

**Issue by Eldrni** [Eldrni/the-elder-bar#8]
When there is a full stack of 200 soul gems and then one additional soul gem, the gadget only shows 1 soul gem total instead of 201.

**Comment by antiseptique** [comment]
I don't know the reason, but actually the gadget display the correct info :
![soulgemsstack](https://user-images.githubusercontent.com/7832217/44953809-ef6d9b80-ae98-11e8-9ebd-043ed677bc46.PNG)

The problem probably appear when in the same game session, and the data refresh correctly when there is a loading, reloadui or game restart, have to test more on that point.

**Comment by Eldrni** [comment]
This refreshes whenever the contents of your character’s bag changes. I’m not using the built in ESO API for soul gems as some people (including me) want to count the free filled soul gems that are given away monthly from the crown store. So I might be doing something wrong.

**Comment by Eldrni** [comment]
No matter what I do, I can't actually reproduce this. I made a couple of changes that *might* fix it, but without being able to actually see it for myself, it's difficult to know if it has any effect. Feel free to re-open this issue after Release 5 comes out next week.
